### ISSUE TITLE
Remove important CSS

### ISSUE THREAD

**Issue by joren485** [GipHouse/Website#441]
### Description

The following CSS is added because of an issue in [django-bootstrap4](https://github.com/zostera/django-bootstrap4/issues/147). Once the issue has been resolved, the CSS should be removed.

```CSS
.invalid-feedback {
    display: block !important;
}
```
